# Generated by Django 2.2.16 on 2022-11-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20221108_1346'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='couple_user_and_author_unique',
        ),
    ]
